# Generated by Django 2.2.6 on 2019-10-19 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_info', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('compensation', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('number_of_positions', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(blank=True, max_length=500)),
                ('GPA', models.FloatField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Student')),
            ],
        ),
    ]
